### ISSUE TITLE
Create folders within node.js

### ISSUE THREAD

**Issue by jansauer** [Qabel/qabel-storage#3]
Is there any particular reason to [use](https://github.com/Qabel/qabel-storage/blob/2c0e1bff687d38d4b73287191144969b1332bac6/app/requestHandler.js#L64-L74) bash scripts for creating and deleting folders?
Why not simply [use](http://nodejs.org/api/fs.html#fs_fs_mkdir_path_mode_callback) `s.mkdir(path, [mode], callback)`?

**Comment by thechauffeur** [comment]
Question is answered. We now have an issue for the future work on it. See #19.
