### ISSUE TITLE
Add a qabel-storage service using S3

### ISSUE THREAD

**Issue by jansauer** [Qabel/qabel-storage#4]
Besides the interesting token usage, qabel-storage seems to be a simple object storage server. So why aren't you using S3 instead?

**Comment by thechauffeur** [comment]
BTW, this issue is in the qabel-storage repository and it has nothing to do with the fact that the qabel-client repository is deprecated.

**Comment by thechauffeur** [comment]
We will provide a S3 solution in the near future.

**Comment by thechauffeur** [comment]
Forgot to close this issue the last time. The statement is nevertheless correct.
